"""added image file

Revision ID: 4a8a0852d35f
Revises: 1b4be23cdd14
Create Date: 2023-10-25 17:59:02.994266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a8a0852d35f'
down_revision = '1b4be23cdd14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.String(length=120), nullable=True))
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.TEXT(), nullable=True))
        batch_op.drop_column('image_file')

    # ### end Alembic commands ###
