"""changed image name

Revision ID: f4cf47d8fc2b
Revises: 59ca5caed6b0
Create Date: 2023-10-26 05:12:55.392371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4cf47d8fc2b'
down_revision = '59ca5caed6b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=120), nullable=True))
        batch_op.drop_column('thumbnail')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail', sa.VARCHAR(length=120), nullable=True))
        batch_op.drop_column('image')

    # ### end Alembic commands ###
